version: '3.1'

services:
  app:
    build:
      context: ./
    container_name: acp-api-app
    restart: always
    ports:
      - "8084:8080"
    networks:
      - proxynet

networks:
  proxynet:
    external: true