spring.mvc.pathmatch.matching-strategy=ant_path_matcher
spring.datasource.url=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.generate-ddl=true

jwt-variables.KEY=${JWT_KEY}
jwt-variables.ISSUER=${JWT_ISSUER}
jwt-variables.EXPIRES_ACCESS_TOKEN_MINUTE=${JWT_EXPIRES_ACCESS_TOKEN_MINUTE}

springdoc.swagger-ui.tagsSorter=alpha
springdoc.swagger-ui.operations-sorter=alpha

file-upload.path=${FILE_UPLOAD_PATH}
media.base-url=${MEDIA_BASE_URL}

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com

spring.servlet.multipart.max-file-size=200MB
spring.servlet.multipart.max-request-size=200MB
server.port=8080
